### ISSUE TITLE
run Demo WARNING: Uninstalling will remove the application data!

### ISSUE THREAD

**Issue by XHiStone** [androidthings/new-project-template#1]
Installation failed with message INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/com.example.androidthings.myproject-1: Package com.example.androidthings.myproject requires unavailable shared library com.google.android.things; failing!.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

click ok and show messages:
$ adb shell pm uninstall com.example.androidthings.myproject
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK

**Comment by jdkoren** [comment]
Which device did you try to run the app on?

**Comment by mangini** [comment]
@18337129968 Apps that use the Android Things library can only be installed in Android Things device. If your app usage of Android Things library is optional, you can add a `requires="false"` property to the `<uses-library>` clause in `AndroidManifest.xml`. Remember in that case to only make calls to the Android Things specific APIs (com.google.android.things.*) after you check that you are running in a valid device, otherwise the method calls will fail.

**Comment by ataulm** [comment]
I have an app that uses the Android Things library if available. Pulling in one of the contrib-driver libraries meant that the `android:required="false"` attribute I had set was being overridden (the manifest-merger uses "OR" to merge `uses-feature` or `uses-library` attributes), leading to the same warning OP got.

In that case, you can use the `tools:replace` marker to explicitly indicate that you want your attribute (in your app's manifest) to replace the resolved (merged) one:

```xml
<uses-library
    android:name="com.google.android.things"
    android:required="false"
    tools:replace="android:required" />
```

>Remember in that case to only make calls to the Android Things specific APIs (com.google.android.things.*) after you check that you are running in a valid device, otherwise the method calls will fail.

still holds true.

**Comment by daj** [comment]
Tip: make sure you put the `<uses-library>` tag inside the `<application>` block.  

The first time I tried this I was putting it in the `<manifest>` block, which doesn't work.  I was able to diagnose my mistake by using Android Studio's `File -> Profile or Debug APK` to open the APK (app/build/outputs/apk/app-debug.apk).

Docs: https://developer.android.com/guide/topics/manifest/uses-library-element.html

**Comment by morgansong** [comment]
Go to menu "Build"-->"Clean Project"-->"Rebuild Project"
Same problem, but works for me.
