### ISSUE TITLE
No scan results

### ISSUE THREAD

**Issue by ivanO86** [androidthings/new-project-template#2]
Hi,

first of all, excuse me if this is not the proper via for this question but I didn't find another site. I am starting a project with intel edison and android things. I'm trying to get a scan result so I have to enable location permissions. In the project overview https://developer.android.com/things/sdk/index.html I can read "Requesting Permissions at Runtime is not supported because embedded devices aren't guaranteed to have a UI to accept the runtime dialog. Declare permissions that you need in your app's manifest file. All normal and dangerous permissions declared in your app's manifest are granted at install time." so I add this permision into the manifest but I don't get any result. When I check the permission in this way

        if (checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            Log.d("MainActivity", "no ACCESS_FINE_LOCATION permision");
        } else {
            Log.d("MainActivity", "ACCESS_COARSE_LOCATION permision granted");
        }

It seems to be disabled. How can I retrieve the scan results?

Thanks.

**Comment by jdkoren** [comment]
Try rebooting the board after installing your app. There is a [known issue](https://developer.android.com/things/preview/releases.html) with developer preview 1 that dangerous permissions are not granted until the device reboots.

**Comment by ivanO86** [comment]
Thanks a lot Jonathan. It works properly now. It was my fault, I didn't check out the release notes of the release.
